#!/bin/bash
# prepare-pr-worktree.sh — Resolves and validates the target repo/worktree for auto-mode execution.
#
# Usage:
#   ./prepare-pr-worktree.sh <REVIEW_DATA_JSON> [--repo-path <path>] [--review-doc <path>]
#     [--worktree auto|<path>]
#
# Output:
#   - Machine-readable JSON on stdout
#   - Human guidance on stderr
#
# Requires: git, jq, gh-authenticated review data generated by fetch-pr.sh

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  prepare-pr-worktree.sh <REVIEW_DATA_JSON> [--repo-path <path>] [--review-doc <path>] [--worktree auto|<path>]

Examples:
  prepare-pr-worktree.sh docs/pr-for-review/[MOVE-658] foo.review-data.json --repo-path /Users/eddie/Desktop/demodev/moving-frontend
  prepare-pr-worktree.sh docs/pr-for-review/[MOVE-658] foo.review-data.json --repo-path /Users/eddie/Desktop/demodev/moving-frontend --review-doc /Users/eddie/Desktop/demodev/moving-frontend/docs/reviews/MOVE-658-review.md --worktree auto
EOF
}

path_within() {
  local base_path="$1"
  local candidate_path="$2"
  case "$candidate_path" in
    "$base_path" | "$base_path"/*) return 0 ;;
    *) return 1 ;;
  esac
}

normalize_path() {
  local raw_path="$1"
  if [ -z "$raw_path" ]; then
    return 0
  fi

  if [ "${raw_path#/}" = "$raw_path" ]; then
    raw_path="$(pwd -P)/$raw_path"
  fi

  if [ -d "$raw_path" ]; then
    (
      cd "$raw_path"
      pwd -P
    )
    return 0
  fi

  local parent_dir
  parent_dir="$(dirname "$raw_path")"
  local suffix
  suffix="$(basename "$raw_path")"
  while [ ! -d "$parent_dir" ] && [ "$parent_dir" != "/" ]; do
    suffix="$(basename "$parent_dir")/${suffix}"
    parent_dir="$(dirname "$parent_dir")"
  done
  (
    cd "$parent_dir"
    printf '%s/%s\n' "$(pwd -P)" "$suffix"
  )
}

normalize_github_repo() {
  printf '%s' "$1" \
    | sed -E 's#^ssh://git@github.com/##; s#^git@github.com:##; s#^https://github.com/##; s#^http://github.com/##; s#\.git$##'
}

extract_last_round_meta() {
  local file_path="$1"
  perl -0ne '
    while (/<!--\s*round_meta:start\s+round=(\d+)\s*-->\s*```json\s*(.*?)\s*```\s*<!--\s*round_meta:end\s+round=\1\s*-->/sg) {
      $last = $2;
    }
    END {
      print $last if defined $last;
    }
  ' "$file_path"
}

extract_ticket_id_from_branch() {
  local branch_name="$1"
  local branch_basename
  branch_basename="$(basename "$branch_name")"

  local matches
  matches="$(printf '%s\n' "$branch_basename" | grep -oE '[A-Z][A-Z0-9]+-[0-9]+' || true)"
  local match_count
  match_count="$(printf '%s\n' "$matches" | sed '/^$/d' | wc -l | tr -d ' ')"

  if [ "$match_count" -eq 1 ]; then
    printf '%s\n' "$matches" | sed '/^$/d' | head -1
    return 0
  fi

  if [ "$match_count" -eq 0 ]; then
    echo "ambiguous: no ticket found in branch basename '${branch_basename}'" >&2
  else
    echo "ambiguous: multiple ticket ids found in branch basename '${branch_basename}'" >&2
  fi
  return 1
}

resolve_review_doc_path() {
  local repo_path="$1"
  local explicit_path="$2"
  local branch_name="$3"

  if [ -n "$explicit_path" ]; then
    local normalized_explicit_path
    normalized_explicit_path="$(normalize_path "$explicit_path")"
    if ! path_within "$repo_path" "$normalized_explicit_path"; then
      echo "Error: Explicit review doc must live inside the resolved target repo: ${normalized_explicit_path}" >&2
      return 1
    fi
    printf '%s\n' "$normalized_explicit_path"
    return 0
  fi

  local ticket_id
  ticket_id="$(extract_ticket_id_from_branch "$branch_name")" || return 1
  printf '%s/docs/reviews/%s-review.md\n' "$repo_path" "$ticket_id"
}

resolve_worktree_review_doc_path() {
  local source_repo_path="$1"
  local target_worktree_path="$2"
  local source_review_doc_path="$3"

  if ! path_within "$source_repo_path" "$source_review_doc_path"; then
    echo "Error: Review doc path must be inside the resolved target repo so it can be mirrored into the prepared worktree: ${source_review_doc_path}" >&2
    return 1
  fi

  local relative_path="${source_review_doc_path#${source_repo_path}/}"
  printf '%s/%s\n' "$target_worktree_path" "$relative_path"
}

seed_review_doc_into_worktree() {
  local source_review_doc_path="$1"
  local target_review_doc_path="$2"

  if [ -f "$target_review_doc_path" ]; then
    printf 'false\n'
    return 0
  fi

  mkdir -p "$(dirname "$target_review_doc_path")"
  cp "$source_review_doc_path" "$target_review_doc_path"
  printf 'true\n'
}

compute_round_context() {
  local review_doc_path="$1"
  local pr_number="$2"

  if [ ! -f "$review_doc_path" ]; then
    jq -n \
      --argjson round_number 1 \
      --arg action "new" \
      --arg status "draft" \
      --arg artifact_dir ".pr-review/pr-${pr_number}/round-1" \
      '{round_number: $round_number, action: $action, status: $status, artifact_dir: $artifact_dir, worktree_path: null}'
    return 0
  fi

  local highest_heading
  highest_heading="$(grep -E '^## .*Round [0-9]+' "$review_doc_path" | sed -E 's/^## .*Round ([0-9]+).*$/\1/' | sort -n | tail -1 || true)"
  if [ -z "$highest_heading" ]; then
    highest_heading=0
  fi

  local last_meta
  last_meta="$(extract_last_round_meta "$review_doc_path")"
  if [ -n "$last_meta" ]; then
    local last_round
    last_round="$(printf '%s' "$last_meta" | jq -r '.round_number // 0')"
    local last_status
    last_status="$(printf '%s' "$last_meta" | jq -r '.status // ""')"
    local last_artifact_dir
    last_artifact_dir="$(printf '%s' "$last_meta" | jq -r '.artifact_dir // empty')"
    local last_worktree_path
    last_worktree_path="$(printf '%s' "$last_meta" | jq -r '.worktree.worktree_path // .worktree.path // empty')"

    if [ "$last_status" = "mutation-partial" ]; then
      jq -n \
        --argjson round_number "$last_round" \
        --arg action "resume" \
        --arg status "$last_status" \
        --arg artifact_dir "$last_artifact_dir" \
        --arg worktree_path "$last_worktree_path" \
        '{round_number: $round_number, action: $action, status: $status, artifact_dir: $artifact_dir, worktree_path: (if $worktree_path == "" then null else $worktree_path end)}'
      return 0
    fi
  fi

  local next_round
  next_round=$((highest_heading + 1))
  jq -n \
    --argjson round_number "$next_round" \
    --arg action "new" \
    --arg status "draft" \
    --arg artifact_dir ".pr-review/pr-${pr_number}/round-${next_round}" \
    '{round_number: $round_number, action: $action, status: $status, artifact_dir: $artifact_dir, worktree_path: null}'
}

ensure_local_exclude() {
  local repo_path="$1"
  local exclude_path
  exclude_path="$(git -C "$repo_path" rev-parse --git-path info/exclude)"

  mkdir -p "$(dirname "$exclude_path")"
  touch "$exclude_path"

  if ! grep -qxF '.pr-review/' "$exclude_path" 2>/dev/null; then
    printf '\n.pr-review/\n' >> "$exclude_path"
  fi

  printf '%s\n' "$exclude_path"
}

emit_json() {
  local status="$1"
  local action="$2"
  local guidance="$3"
  local created="$4"
  local reused="$5"
  local source_dirty="$6"
  local head_matches="$7"
  local target_path="$8"
  local repo_path="$9"
  local expected_repo="${10}"
  local push_remote="${11}"
  local push_branch="${12}"
  local expected_head_sha="${13}"
  local actual_head_sha="${14}"
  local review_doc_path="${15}"
  local round_context_json="${16}"
  local worktree_mode="${17}"
  local exclude_path="${18}"
  local current_branch="${19}"
  local source_review_doc_path="${20}"
  local review_doc_seeded="${21}"

  jq -n \
    --arg status "$status" \
    --arg action "$action" \
    --arg guidance "$guidance" \
    --arg repo_path "$repo_path" \
    --arg source_repo_path "$repo_path" \
    --arg worktree_path "$target_path" \
    --arg expected_repo "$expected_repo" \
    --arg push_remote "$push_remote" \
    --arg push_branch "$push_branch" \
    --arg expected_head_sha "$expected_head_sha" \
    --arg actual_head_sha "$actual_head_sha" \
    --arg review_doc_path "$review_doc_path" \
    --arg worktree_mode "$worktree_mode" \
    --arg exclude_path "$exclude_path" \
    --arg current_branch "$current_branch" \
    --arg source_review_doc_path "$source_review_doc_path" \
    --argjson created "$created" \
    --argjson reused "$reused" \
    --argjson source_dirty "$source_dirty" \
    --argjson head_matches "$head_matches" \
    --argjson round_context "$round_context_json" \
    --argjson review_doc_seeded "$review_doc_seeded" \
    '
      {
        status: $status,
        action: $action,
        guidance: (if $guidance == "" then null else $guidance end),
        repo_path: (if $repo_path == "" then null else $repo_path end),
        source_repo_path: (if $source_repo_path == "" then null else $source_repo_path end),
        worktree_mode: $worktree_mode,
        worktree_path: (if $worktree_path == "" then null else $worktree_path end),
        created: $created,
        reused: $reused,
        source_repo_dirty: $source_dirty,
        expected_repo: $expected_repo,
        push_remote: $push_remote,
        push_branch: $push_branch,
        expected_head_sha: $expected_head_sha,
        actual_head_sha: $actual_head_sha,
        head_matches_expected: $head_matches,
        current_branch: (if $current_branch == "" then null else $current_branch end),
        review_doc_path: (if $review_doc_path == "" then null else $review_doc_path end),
        source_review_doc_path: (if $source_review_doc_path == "" then null else $source_review_doc_path end),
        review_doc_seeded: $review_doc_seeded,
        exclude_path: (if $exclude_path == "" then null else $exclude_path end),
        round_number: ($round_context.round_number // null),
        round_action: ($round_context.action // null),
        round_status: ($round_context.status // null),
        artifact_dir: ($round_context.artifact_dir // null),
        recorded_worktree_path: ($round_context.worktree_path // null)
      }
    '
}

REPO_PATH=""
REVIEW_DOC_PATH=""
WORKTREE_ARG=""
POSITIONAL=()
REPO_PATH_WAS_EXPLICIT=false

while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo-path)
      REPO_PATH="${2:?Missing value for --repo-path}"
      REPO_PATH_WAS_EXPLICIT=true
      shift 2
      ;;
    --review-doc)
      REVIEW_DOC_PATH="${2:?Missing value for --review-doc}"
      shift 2
      ;;
    --worktree)
      WORKTREE_ARG="${2:?Missing value for --worktree}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      POSITIONAL+=("$1")
      shift
      ;;
  esac
done

if [ "${#POSITIONAL[@]}" -lt 1 ]; then
  usage >&2
  exit 1
fi

REVIEW_DATA_FILE="${POSITIONAL[0]}"
if [ ! -f "$REVIEW_DATA_FILE" ]; then
  echo "Error: Review data file not found: ${REVIEW_DATA_FILE}" >&2
  exit 1
fi

EXPECTED_REPO="$(jq -r '.pr.head_repo // .pr.repo' "$REVIEW_DATA_FILE")"
EXPECTED_BRANCH="$(jq -r '.pr.branch' "$REVIEW_DATA_FILE")"
EXPECTED_HEAD_SHA="$(jq -r '.pr.head_sha' "$REVIEW_DATA_FILE")"
PR_NUMBER="$(jq -r '.pr.number' "$REVIEW_DATA_FILE")"

if [ -n "$REPO_PATH" ]; then
  REPO_PATH="$(normalize_path "$REPO_PATH")"
else
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    REPO_PATH="$(git rev-parse --show-toplevel)"
  else
    guidance="Could not resolve the target repo from the current working directory. Re-run with --repo-path <abs-path>."
    echo "$guidance" >&2
    emit_json "needs-repo-path" "stop" "$guidance" false false false false \
      "" "" "$EXPECTED_REPO" "" "$EXPECTED_BRANCH" "$EXPECTED_HEAD_SHA" "" \
      "$REVIEW_DOC_PATH" "{}" "none" "" "" "" false
    exit 2
  fi
fi

if ! git -C "$REPO_PATH" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Error: Repo path is not a git repository: ${REPO_PATH}" >&2
  exit 1
fi

SOURCE_REPO_PATH="$(normalize_path "$REPO_PATH")"
SOURCE_DIRTY_JSON=false
if [ -n "$(git -C "$SOURCE_REPO_PATH" status --porcelain --untracked-files=all)" ]; then
  SOURCE_DIRTY_JSON=true
fi

CURRENT_BRANCH="$(git -C "$SOURCE_REPO_PATH" branch --show-current || true)"
CURRENT_HEAD_SHA="$(git -C "$SOURCE_REPO_PATH" rev-parse HEAD)"

MATCHING_REMOTES=()
while read -r remote_name; do
  [ -z "$remote_name" ] && continue
  remote_url="$(git -C "$SOURCE_REPO_PATH" remote get-url --push "$remote_name" 2>/dev/null || git -C "$SOURCE_REPO_PATH" remote get-url "$remote_name" 2>/dev/null || true)"
  if [ -n "$remote_url" ] && [ "$(normalize_github_repo "$remote_url")" = "$EXPECTED_REPO" ]; then
    MATCHING_REMOTES+=("$remote_name")
  fi
done < <(git -C "$SOURCE_REPO_PATH" remote)

if [ "${#MATCHING_REMOTES[@]}" -eq 0 ]; then
  if [ "$REPO_PATH_WAS_EXPLICIT" = "true" ]; then
    echo "Error: Repo ${SOURCE_REPO_PATH} does not match the PR head repo ${EXPECTED_REPO}. Pass the correct --repo-path." >&2
    exit 1
  fi

  guidance="The current working directory is not the PR target repo. Re-run with --repo-path <abs-path>."
  echo "$guidance" >&2
  emit_json "needs-repo-path" "stop" "$guidance" false false "$SOURCE_DIRTY_JSON" false \
    "$SOURCE_REPO_PATH" "$SOURCE_REPO_PATH" "$EXPECTED_REPO" "" "$EXPECTED_BRANCH" \
    "$EXPECTED_HEAD_SHA" "$CURRENT_HEAD_SHA" "$REVIEW_DOC_PATH" "{}" "none" "" "$CURRENT_BRANCH" "" false
  exit 2
fi

PUSH_REMOTE="$(git -C "$SOURCE_REPO_PATH" config "branch.${EXPECTED_BRANCH}.pushRemote" || true)"
if [ -z "$PUSH_REMOTE" ]; then
  PUSH_REMOTE="$(git -C "$SOURCE_REPO_PATH" config remote.pushDefault || true)"
fi
if [ -z "$PUSH_REMOTE" ]; then
  PUSH_REMOTE="$(git -C "$SOURCE_REPO_PATH" config "branch.${EXPECTED_BRANCH}.remote" || true)"
fi
if [ -z "$PUSH_REMOTE" ]; then
  PUSH_REMOTE="${MATCHING_REMOTES[0]}"
fi

PUSH_REMOTE_MATCH=false
for candidate_remote in "${MATCHING_REMOTES[@]}"; do
  if [ "$candidate_remote" = "$PUSH_REMOTE" ]; then
    PUSH_REMOTE_MATCH=true
    break
  fi
done

if [ "$PUSH_REMOTE_MATCH" != "true" ]; then
  echo "Error: The selected push remote (${PUSH_REMOTE}) does not match the PR head repo ${EXPECTED_REPO}." >&2
  exit 1
fi

git -C "$SOURCE_REPO_PATH" fetch --quiet "$PUSH_REMOTE" "$EXPECTED_BRANCH"
REMOTE_REF="refs/remotes/${PUSH_REMOTE}/${EXPECTED_BRANCH}"
if ! git -C "$SOURCE_REPO_PATH" show-ref --verify --quiet "$REMOTE_REF"; then
  echo "Error: Remote branch ${PUSH_REMOTE}/${EXPECTED_BRANCH} was not found in ${SOURCE_REPO_PATH}." >&2
  exit 1
fi

REMOTE_HEAD_SHA="$(git -C "$SOURCE_REPO_PATH" rev-parse "$REMOTE_REF")"
if [ "$REMOTE_HEAD_SHA" != "$EXPECTED_HEAD_SHA" ]; then
  echo "Error: Remote branch ${PUSH_REMOTE}/${EXPECTED_BRANCH} is at ${REMOTE_HEAD_SHA}, but review data expects ${EXPECTED_HEAD_SHA}. Re-run fetch-pr.sh." >&2
  exit 1
fi

REVIEW_DOC_PATH="$(resolve_review_doc_path "$SOURCE_REPO_PATH" "$REVIEW_DOC_PATH" "$EXPECTED_BRANCH")" || {
  echo "Error: Could not resolve the review doc. Pass --review-doc <path>." >&2
  exit 1
}
SOURCE_REVIEW_DOC_CANONICAL_PATH="$REVIEW_DOC_PATH"
SOURCE_REVIEW_DOC_PATH=""
if [ -f "$REVIEW_DOC_PATH" ]; then
  SOURCE_REVIEW_DOC_PATH="$REVIEW_DOC_PATH"
fi
ROUND_CONTEXT_JSON="$(compute_round_context "$REVIEW_DOC_PATH" "$PR_NUMBER")"

if [ -z "$WORKTREE_ARG" ]; then
  if [ "$CURRENT_BRANCH" != "$EXPECTED_BRANCH" ]; then
    echo "Error: Current branch is '${CURRENT_BRANCH:-DETACHED}', but the PR head branch is '${EXPECTED_BRANCH}'." >&2
    exit 1
  fi

  if [ "$CURRENT_HEAD_SHA" != "$EXPECTED_HEAD_SHA" ]; then
    echo "Error: Current HEAD is ${CURRENT_HEAD_SHA}, but the PR head SHA is ${EXPECTED_HEAD_SHA}. Fetch/reset the branch or use --worktree." >&2
    exit 1
  fi

  if [ "$SOURCE_DIRTY_JSON" = "true" ]; then
    guidance="Target repo is dirty. Re-run with --worktree auto or --worktree /abs/path to continue safely."
    echo "$guidance" >&2
    emit_json "needs-worktree" "stop" "$guidance" false false "$SOURCE_DIRTY_JSON" true \
      "$SOURCE_REPO_PATH" "$SOURCE_REPO_PATH" "$EXPECTED_REPO" "$PUSH_REMOTE" "$EXPECTED_BRANCH" \
      "$EXPECTED_HEAD_SHA" "$CURRENT_HEAD_SHA" "$REVIEW_DOC_PATH" "$ROUND_CONTEXT_JSON" "none" "" "$CURRENT_BRANCH" "$SOURCE_REVIEW_DOC_PATH" false
    exit 2
  fi

  EXCLUDE_PATH="$(ensure_local_exclude "$SOURCE_REPO_PATH")"
  emit_json "ready" "in-place" "" false false "$SOURCE_DIRTY_JSON" true \
    "$SOURCE_REPO_PATH" "$SOURCE_REPO_PATH" "$EXPECTED_REPO" "$PUSH_REMOTE" "$EXPECTED_BRANCH" \
    "$EXPECTED_HEAD_SHA" "$CURRENT_HEAD_SHA" "$REVIEW_DOC_PATH" "$ROUND_CONTEXT_JSON" "in-place" "$EXCLUDE_PATH" "$CURRENT_BRANCH" "$SOURCE_REVIEW_DOC_PATH" false
  exit 0
fi

ROUND_ACTION="$(printf '%s' "$ROUND_CONTEXT_JSON" | jq -r '.action // "new"')"
ROUND_NUMBER="$(printf '%s' "$ROUND_CONTEXT_JSON" | jq -r '.round_number // empty')"
RECORDED_WORKTREE_PATH="$(printf '%s' "$ROUND_CONTEXT_JSON" | jq -r '.worktree_path // empty')"

if [ "$WORKTREE_ARG" = "auto" ]; then
  if [ -z "$ROUND_NUMBER" ]; then
    echo "Error: Auto worktree mode requires a resolved review doc so the round number can be determined." >&2
    exit 1
  fi

  if [ -n "$RECORDED_WORKTREE_PATH" ] && [ "$ROUND_ACTION" = "resume" ]; then
    TARGET_WORKTREE_PATH="$RECORDED_WORKTREE_PATH"
  else
    REPO_PATH_HASH="$(printf '%s' "$SOURCE_REPO_PATH" | shasum -a 256 | awk '{print substr($1, 1, 8)}')"
    TARGET_WORKTREE_PATH="$(dirname "$SOURCE_REPO_PATH")/$(printf '%s' "$EXPECTED_REPO" | tr '/.' '-')-pr-${PR_NUMBER}-round-${ROUND_NUMBER}-${REPO_PATH_HASH}"
  fi
  WORKTREE_MODE="auto"
else
  TARGET_WORKTREE_PATH="$(normalize_path "$WORKTREE_ARG")"
  WORKTREE_MODE="explicit"
fi

CREATED_JSON=false
REUSED_JSON=false

if [ -e "$TARGET_WORKTREE_PATH" ]; then
  if ! git -C "$TARGET_WORKTREE_PATH" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Error: Existing worktree path is not a git worktree: ${TARGET_WORKTREE_PATH}" >&2
    exit 1
  fi

  existing_remote_match=false
  while read -r remote_name; do
    [ -z "$remote_name" ] && continue
    remote_url="$(git -C "$TARGET_WORKTREE_PATH" remote get-url --push "$remote_name" 2>/dev/null || git -C "$TARGET_WORKTREE_PATH" remote get-url "$remote_name" 2>/dev/null || true)"
    if [ -n "$remote_url" ] && [ "$(normalize_github_repo "$remote_url")" = "$EXPECTED_REPO" ]; then
      existing_remote_match=true
      break
    fi
  done < <(git -C "$TARGET_WORKTREE_PATH" remote)

  if [ "$existing_remote_match" != "true" ]; then
    echo "Error: Existing worktree path does not belong to the PR head repo ${EXPECTED_REPO}: ${TARGET_WORKTREE_PATH}" >&2
    exit 1
  fi

  if [ -n "$(git -C "$TARGET_WORKTREE_PATH" status --porcelain --untracked-files=all)" ]; then
    echo "Error: Existing worktree is dirty and cannot be reused safely: ${TARGET_WORKTREE_PATH}" >&2
    exit 1
  fi

  TARGET_HEAD_SHA="$(git -C "$TARGET_WORKTREE_PATH" rev-parse HEAD)"
  if [ "$ROUND_ACTION" != "resume" ] && [ "$TARGET_HEAD_SHA" != "$EXPECTED_HEAD_SHA" ]; then
    echo "Error: Existing worktree HEAD ${TARGET_HEAD_SHA} does not match expected PR head ${EXPECTED_HEAD_SHA}: ${TARGET_WORKTREE_PATH}" >&2
    exit 1
  fi

  REUSED_JSON=true
else
  if [ "$ROUND_ACTION" = "resume" ]; then
    echo "Error: Round ${ROUND_NUMBER} is marked mutation-partial, but its recorded worktree does not exist anymore: ${TARGET_WORKTREE_PATH}" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$TARGET_WORKTREE_PATH")"
  git -C "$SOURCE_REPO_PATH" worktree add --detach "$TARGET_WORKTREE_PATH" "$REMOTE_REF" >/dev/null
  CREATED_JSON=true
fi

TARGET_HEAD_SHA="$(git -C "$TARGET_WORKTREE_PATH" rev-parse HEAD)"
HEAD_MATCHES_JSON=true
if [ "$ROUND_ACTION" != "resume" ] && [ "$TARGET_HEAD_SHA" != "$EXPECTED_HEAD_SHA" ]; then
  HEAD_MATCHES_JSON=false
  echo "Error: Prepared worktree HEAD ${TARGET_HEAD_SHA} does not match expected PR head ${EXPECTED_HEAD_SHA}: ${TARGET_WORKTREE_PATH}" >&2
  exit 1
fi

EXCLUDE_PATH="$(ensure_local_exclude "$TARGET_WORKTREE_PATH")"
WORKTREE_REVIEW_DOC_PATH="$REVIEW_DOC_PATH"
REVIEW_DOC_SEEDED=false
if [ -n "$SOURCE_REVIEW_DOC_CANONICAL_PATH" ]; then
  WORKTREE_REVIEW_DOC_PATH="$(resolve_worktree_review_doc_path "$SOURCE_REPO_PATH" "$TARGET_WORKTREE_PATH" "$SOURCE_REVIEW_DOC_CANONICAL_PATH")" || exit 1
  mkdir -p "$(dirname "$WORKTREE_REVIEW_DOC_PATH")"
fi
if [ -n "$SOURCE_REVIEW_DOC_PATH" ]; then
  REVIEW_DOC_SEEDED="$(seed_review_doc_into_worktree "$SOURCE_REVIEW_DOC_PATH" "$WORKTREE_REVIEW_DOC_PATH")"
fi
emit_json "ready" "${ROUND_ACTION}" "" "$CREATED_JSON" "$REUSED_JSON" "$SOURCE_DIRTY_JSON" "$HEAD_MATCHES_JSON" \
  "$TARGET_WORKTREE_PATH" "$SOURCE_REPO_PATH" "$EXPECTED_REPO" "$PUSH_REMOTE" "$EXPECTED_BRANCH" \
  "$EXPECTED_HEAD_SHA" "$TARGET_HEAD_SHA" "$WORKTREE_REVIEW_DOC_PATH" "$ROUND_CONTEXT_JSON" "$WORKTREE_MODE" "$EXCLUDE_PATH" "$(git -C "$TARGET_WORKTREE_PATH" branch --show-current || true)" "$SOURCE_REVIEW_DOC_PATH" "$REVIEW_DOC_SEEDED"
